### ISSUE TITLE
self-oscillation? 

### ISSUE THREAD

**Issue by pppier** [ThoEvans/Eurorack#1]
hello, 
built a unit, beautiful deign, thanks for you work
testing it, i hear both 1 and 2 lpf does a crackle, when high resonance, and cutoff is high (spread at noon) usually when i meet this behaviour, there are suggestion to additional cap to avoid the selfosc. ...
i think the only caps to look at are the 220p, what do you think? have you expereinced it in your build? 
i have not the "hihat" behaviour, they both give a little noise on high cutoff (and max res) but not so usable...
(v2164 from thonk)
what do you think? :-)

**Comment by ThoEvans** [comment]
The issue was finally pinpointed to a phenomenon new to me known as "Squegging." 
(Big thanks to Mike D!)

Due to the control circuit behavior, the frequency range of the filter went well past audio range when the cutoff was turned up. This has been addressed in Rev 4 where 7 resistor values on the control board were changed.

The new Rev 4 BOM is available now and has info on which resistors were changed and to what new values.
